### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [az879593/git-practice#1]
- 好奇問一下，既然你都知道 websocket 了，為什麼不用用看？
- git.md 這份作業，回答問題的部分還可以，但建議編排一下。試試看做作業時，除了在技術上完整回答外，也試著練習寫出別人容易閱讀的編排來，讓一份作業發揮多重練習的價值。
- 「git repo中的變化」這題，希望你能試著記錄自己具體觀察到的變化，你目前寫得比較像是觀察後的結論，這部分要有，但觀察過程也要有。例如你這樣寫
> 假設今天git add a.txt b.txt兩份檔案，裡面內容皆為hello world
> 會因為它們皆是透過內容來hash，hash出來的值一樣，兩個都會存取到同一份檔案，而不是a.txt和b.txt個別建立一份在.git裡面

那我想請問，你怎麼證明你寫的這句話是對的？也就是 git 真的是如你這句話所描述那樣在做事呢？

**Comment by az879593** [comment]
老師您好，由於您是寄到github去，所以這封信跑到我的另一個mail了，因此換一個信箱回覆您

先回答2. 3.
2. 了解，或許我可以用一個範例來連續的說這幾個物件的概念
3. 這部分可能可以在文件搭配一些圖片或影片來證明這些事情
關於1.
當初這是一個學校的專案，題目不限但要有會員系統，建議做電商平台這樣
但當初覺得這個不夠有趣，所以我們決定做一個交友軟體，主要以會員、配對和聊天作為三個主要功能
因為有很多都是從零開始，所以一開始並沒有想到一些問題，很多都是在開發中遇到才去解決
而後來了解到有websocket這個技術可以用來開發real-time的聊天系統時
我們認為距離demo所剩的時間去學習這個來應用其實有一點風險，可能會導致當天無法成功demo
而該課程demo也沒有架到伺服端需求，更沒有用戶壓力等問題
因此最後決定先採用ajax去刷新，確保當天能夠展示
而做完這專案後我也有想過要不要自己重構看看(在後來還有修過一門ooad的課，感覺之前寫很多爛code)
但這專案做完後我就差不多開始準備研究所考試，考完後又找了一個實習
變得那陣子有點太忙，要邊實習邊上課和準備報paper
有點拖著拖著就拖到現在了XD

azole ***@***.***> 於 2024年9月19日 週四 上午2:55寫道：

**Comment by azole** [comment]
用圖片輔助是很好的一種方式，另外句子的排版，關於這點，你先思考看看，或先試試看，課堂上會舉例。
<img width="778" alt="image" src="https://github.com/user-attachments/assets/97d0a3d9-4cc0-448f-a374-52564f6d431a">

**Comment by azole** [comment]
看過課堂上分享的其他同學的作業，有感受到我說的排版這件事嗎？

**Comment by azole** [comment]
嗯嗯，很好耶，能看到別人做得好的地方，是很好的第一步，你可以從現在開始，建立你自己的寫作風格，這件事沒有標準答案，可能有幾種方式你可以練習試試看：

- 多去看別人的成果，看的時候不要只看技術或內容本身，也學習對方的呈現方式
- 自己寫完後不要停下來，回頭多閱讀幾次，甚至隔一天後，再回來看，多問自己: 閱讀起來通順嗎？舒服嗎？讀得下去嗎？

慢慢的你就可以建立出屬於自己的風格，未來在職涯中，會很需要這樣呈現自己成果的能力，當個技術跟表達都很強的工程師吧！

**Comment by azole** [comment]
這個 issue 你可以 close 了，期待你下次的作業！
